### ISSUE TITLE
Libgcrypt compilation issue for windows

### ISSUE THREAD

**Issue by badr-badri** [Ace17/zenbuild#2]
Actually Libgcrypt does not compile as it should for windows platform. While I try to compile for x86_64-w64-mingw32 I get this error :

../../../compat/../src/gcrypt.h:32:23: fatal error: gpg-error.h: No such file or directory
#include
^
compilation terminated.
Makefile:390: recipe for target 'compat.lo' failed

When I copy the file "gpg-error.h" to src directory the compilation takes again but stops at this error :

/tmp/ccMx5oGS.s: Assembler messages:
/tmp/ccMx5oGS.s:27: Error: unsupported instruction `mov'
Makefile:401: recipe for target 'rndhw.lo' failed
make[2]: *** [rndhw.lo] Error 1
make[2]: Leaving directory '/tmp/gcrypt_a/src/libgcrypt/build/x86_64-w64-mingw32/random'

These issues don't appear when I compile for Linux platform

**Comment by Ace17** [comment]
Hi Badr,
Thanks for reporting. I'm having a look at this.

**Comment by Ace17** [comment]
ok, workarounded.
