### ISSUE TITLE
openh264 compilation issue for i686-w64-mingw32

### ISSUE THREAD

**Issue by ghost** [Ace17/zenbuild#3]
I get this error when I try to compile openh264 for the i686-w64-mingw32 architecture:

/usr/bin/ld: option « --out-implib » non reocnnue
/usr/bin/ld: utiliser --help pour afficher l'aide-mémoire
collect2: error: ld returned 1 exit status
Makefile:205: recipe for target 'libopenh264.dll' failed
make: **\* [libopenh264.dll] Error 1

I guess that it's related to ld binary. Any idea to fix that ?

**Comment by Ace17** [comment]
Seems like a cross prefix related issue.
Using native /usr/bin/ld is very unlikely to work in a cross-compilation scenario.

I try to get it to compile today, but I gave up upon the ridiculously long download/clone time of the openh264 archive.

**Comment by Ace17** [comment]
ok fixed.
